// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlatBuffersCounter struct {
	_tab flatbuffers.Table
}

func GetRootAsFlatBuffersCounter(buf []byte, offset flatbuffers.UOffsetT) *FlatBuffersCounter {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlatBuffersCounter{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FlatBuffersCounter) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlatBuffersCounter) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FlatBuffersCounter) ID(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FlatBuffersCounter) IDLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FlatBuffersCounter) IDBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FlatBuffersCounter) Value() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FlatBuffersCounter) MutateValue(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func FlatBuffersCounterStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FlatBuffersCounterAddID(builder *flatbuffers.Builder, ID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ID), 0)
}
func FlatBuffersCounterStartIDVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func FlatBuffersCounterAddValue(builder *flatbuffers.Builder, Value int64) {
	builder.PrependInt64Slot(1, Value, 0)
}
func FlatBuffersCounterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
