// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlatBuffersBatchTimer struct {
	_tab flatbuffers.Table
}

func GetRootAsFlatBuffersBatchTimer(buf []byte, offset flatbuffers.UOffsetT) *FlatBuffersBatchTimer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlatBuffersBatchTimer{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FlatBuffersBatchTimer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlatBuffersBatchTimer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FlatBuffersBatchTimer) ID(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FlatBuffersBatchTimer) IDLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FlatBuffersBatchTimer) IDBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FlatBuffersBatchTimer) Values(j int) float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *FlatBuffersBatchTimer) ValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func FlatBuffersBatchTimerStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FlatBuffersBatchTimerAddID(builder *flatbuffers.Builder, ID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ID), 0)
}
func FlatBuffersBatchTimerStartIDVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func FlatBuffersBatchTimerAddValues(builder *flatbuffers.Builder, Values flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Values), 0)
}
func FlatBuffersBatchTimerStartValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func FlatBuffersBatchTimerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
