// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers

const (
	TypeUnknownType = 0
	TypeCounterType = 1
	TypeBatchTimerType = 2
	TypeGaugeType = 3
)

var EnumNamesType = map[int]string{
	TypeUnknownType:"UnknownType",
	TypeCounterType:"CounterType",
	TypeBatchTimerType:"BatchTimerType",
	TypeGaugeType:"GaugeType",
}

